AWSTemplateFormatVersion: '2010-09-09'
################################################################################
#
# DESCRIPTION
#
##############################################################################
################################################################################
#
# RESOURCES
#
##############################################################################
Resources:
  rECRRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: hello-server

  rECRRepoParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: ECR Repository
      Name: ecr-repo-name
      Type: String
      Value: !Ref rECRRepo

  rECSLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/hello-server

  rTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Name: hello-server
          Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/hello-server
          PortMappings:
            - ContainerPort: 80
              HostPort: 80
              Protocol: tcp
          Essential: true
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/hello-server
              awslogs-region: eu-west-1
              awslogs-stream-prefix: ecs
      Family: hello-server
      NetworkMode: bridge
      Memory: 256
      RequiresCompatibilities:
            - EC2

  rTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: hello-server-tg
      TargetType: instance
      HealthCheckIntervalSeconds: 5
      HealthCheckPath: /ping
      HealthCheckTimeoutSeconds: 3
      HealthyThresholdCount: 2
      Port: 80
      Protocol: HTTP
      VpcId: !Sub '{{resolve:ssm:vpc}}'
      TargetGroupAttributes:
      - Key: deregistration_delay.timeout_seconds
        Value: '5'

  rListenerRule:
    Type: 'AWS::ElasticLoadBalancingV2::ListenerRule'
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn: !Ref rTargetGroup
      Conditions:
        - Field: path-pattern
          PathPatternConfig:
            Values:
              - "/hello/*"
      ListenerArn: !Sub '{{resolve:ssm:public-lb-listener}}'
      Priority: 10

  rCodeBuildLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /codebuild/hello-server
###############################################################################
#
# OUTPUTS
#
###############################################################################
Outputs:
  ECSTaskDefinition:
    Description: The created Taskdefinition.
    Value: !Ref rTaskDefinition